### ISSUE TITLE
MCQAData is not defined anywhere?

### ISSUE THREAD

**Issue by monk1337** [mcQA-suite/mcQA#46]
I am trying to run the example, getting this error : 
`ImportError: cannot import name 'MCQAData' from 'mcqa.data'`

There is no MCQAData function.

**Comment by tayciryahmed** [comment]
Thank you for the feedback. The example and documentation need to be updated. In the meanwhile, below is a code snippet to get you started with the experiment:

```python
from transformers import AutoTokenizer
from mcqa.data import McqaDataset, Split
from mcqa.models import Model

tokenizer = AutoTokenizer.from_pretrained(
        'bert-base-uncased',
        cache_dir='/tmp',
    )

mcqa_dataset = McqaDataset(
        data_dir=data_path,
        tokenizer=tokenizer,
        task='swag',
        max_seq_length=512,
        overwrite_cache=False,
        mode=Split.train,
    )

mdl = Model(bert_model="bert-base-uncased",
                device="cpu")

mdl.fit(mcqa_dataset.get_dataset(),
            train_batch_size=16,
            num_train_epochs=10)
```

**Comment by monk1337** [comment]
I am using the above script and getting this error :

```
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Iteration:   0%|                                                                           | 0/32 [00:02<?, ?it/s]
Epoch:   0%|                                                                               | 0/10 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    num_train_epochs=10)
  File "/home/mcQA/mcqa/models/model.py", line 248, in fit
    input_mask, label_ids).to("cuda:0")[0]
  File "/home/mcQA/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mcQA/env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/mcQA/env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/mcQA/env/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/mcQA/env/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/mcQA/env/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/mcQA/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mcQA/env/lib/python3.6/site-packages/transformers/modeling_bert.py", line 1456, in forward
    return_dict=return_dict,
  File "/home/mcQA/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mcQA/env/lib/python3.6/site-packages/transformers/modeling_bert.py", line 838, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "/home/mcQA/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mcQA/env/lib/python3.6/site-packages/transformers/modeling_bert.py", line 201, in forward
    embeddings = inputs_embeds + position_embeddings + token_type_embeddings
RuntimeError: The size of tensor a (32) must match the size of tensor b (11) at non-singleton dimension 1
```
